### ISSUE TITLE
Can't find the highD.config in highD4traci.py

### ISSUE THREAD

**Issue by fantastic8124** [SCP-CN-001/trajectory_dataset_support#1]
Hi! Thanks for the excellent work!

I wonder where is the highD.config in the [utils](https://github.com/SCP-CN-001/trajectory_dataset_support/tree/main/utils)
/highD4traci.py,  or Ineed to write this file by myself?
Because the current repo does not have this file, so I am unable to successfully run the data processing in highD4traci.py

Thanks for your time!

**Comment by MotacillaAlba** [comment]
I am glad this repository can help you!

highD.config is now merged into [map/map.config](https://github.com/SCP-CN-001/trajectory_dataset_support/blob/main/map/map.config). The highD4traci.py script has been deprecated. I plan to remove it in future updates, so please be careful when using it.

You may find my other work on simulator helpful too (https://github.com/WoodOxen/tactics2d)

**Comment by fantastic8124** [comment]
> I am glad this repository can help you!
> 
> highD.config is now merged into [map/map.config](https://github.com/SCP-CN-001/trajectory_dataset_support/blob/main/map/map.config). The highD4traci.py script has been deprecated. I plan to remove it in future updates, so please be careful when using it.
> 
> You may find my other work on simulator helpful too (https://github.com/WoodOxen/tactics2d)

Thanks for the answer!
If the highD4traci.py script has been deprecated, do we still need to convert the data format? 
Because I found that when running the Sumo_traci.py script, unprocessed HighD datasets cannot be directly used, meaning that unprocessed HighD datasets lack labels such as "angle" to match the need of SUMO TraCi.

**Comment by MotacillaAlba** [comment]
> > I am glad this repository can help you!
> > highD.config is now merged into [map/map.config](https://github.com/SCP-CN-001/trajectory_dataset_support/blob/main/map/map.config). The highD4traci.py script has been deprecated. I plan to remove it in future updates, so please be careful when using it.
> > You may find my other work on simulator helpful too (https://github.com/WoodOxen/tactics2d)
> 
> Thanks for the answer! If the highD4traci.py script has been deprecated, do we still need to convert the data format? Because I found that when running the Sumo_traci.py script, unprocessed HighD datasets cannot be directly used, meaning that unprocessed HighD datasets lack labels such as "angle" to match the need of SUMO TraCi.

Yes, it is always necessary to convert the data format. 

I see there remains a need for highD2traci data converter now. I will create a new interface to aggregate this function in future development.

**Comment by fantastic8124** [comment]
> > > I am glad this repository can help you!
> > > highD.config is now merged into [map/map.config](https://github.com/SCP-CN-001/trajectory_dataset_support/blob/main/map/map.config). The highD4traci.py script has been deprecated. I plan to remove it in future updates, so please be careful when using it.
> > > You may find my other work on simulator helpful too (https://github.com/WoodOxen/tactics2d)
> > 
> > 
> > Thanks for the answer! If the highD4traci.py script has been deprecated, do we still need to convert the data format? Because I found that when running the Sumo_traci.py script, unprocessed HighD datasets cannot be directly used, meaning that unprocessed HighD datasets lack labels such as "angle" to match the need of SUMO TraCi.
> 
> Yes, it is always necessary to convert the data format.
> 
> I see there remains a need for highD2traci data converter now. I will create a new interface to aggregate this function in future development.

OK Thanks! I understand. 
May I ask if it is convenient for you to provide a template or demo of the original HighD.config file? I would like to rewrite this file to complete the data processing for further application.
Thank you for your help！

**Comment by MotacillaAlba** [comment]
> > > > I am glad this repository can help you!
> > > > highD.config is now merged into [map/map.config](https://github.com/SCP-CN-001/trajectory_dataset_support/blob/main/map/map.config). The highD4traci.py script has been deprecated. I plan to remove it in future updates, so please be careful when using it.
> > > > You may find my other work on simulator helpful too (https://github.com/WoodOxen/tactics2d)
> > > 
> > > 
> > > Thanks for the answer! If the highD4traci.py script has been deprecated, do we still need to convert the data format? Because I found that when running the Sumo_traci.py script, unprocessed HighD datasets cannot be directly used, meaning that unprocessed HighD datasets lack labels such as "angle" to match the need of SUMO TraCi.
> > 
> > 
> > Yes, it is always necessary to convert the data format.
> > I see there remains a need for highD2traci data converter now. I will create a new interface to aggregate this function in future development.
> 
> OK Thanks! I understand. May I ask if it is convenient for you to provide a template or demo of the original HighD.config file? I would like to rewrite this file to complete the data processing for further application. Thank you for your help！

I guess this version will work for you: https://github.com/SCP-CN-001/trajectory_dataset_support/blob/d24bc3c6d3af1bb05c965b3d688aa2e8c3f77930/utils/highD.config

Good luck!
