### ISSUE TITLE
[Help wanted] Failed to convert highD_1 osm files using SUMO netconvert tools 

### ISSUE THREAD

**Issue by gcruiser** [SCP-CN-001/trajectory_dataset_support#2]
Hi, while using SUMO to convert osm network files from highD and inD, I have been unable to convert resulting in the following error:
`  netconvert --osm-files highD_1.osm -o hd1.net.xml
  Error: No nodes loaded.
  Quitting (on error).`
But when I tried to convert the map exported directly from the OSM website, I was successful, so I am sure there is ok with the environment configuration;
I wondered how you handled this issue at the time?

**Comment by MotacillaAlba** [comment]
This is not a surprising issue, considering that we used JOSM and [Lanelet2](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master) standards to build the maps. Currently, we have not tested the map's compatibility with SUMO yet. 

We do have a plan to add interface support to SUMO in Tactics2D V1.1.0. Please follow our updates in [Tactics2D](https://github.com/WoodOxen/tactics2d). You can also join our discord community by this link: https://discord.gg/Ha7Ns7jg.

**Comment by gcruiser** [comment]
I understand, thanks for your suggestion.
I want to ask how I can obtain SUMO network files such as highD_1.net.xml? 
Because I currently have another road network file built by JOSM, I want to convert it into a SUMO road network file, similar to what this repo does.

**Comment by MotacillaAlba** [comment]
> I understand, thanks for your suggestion. I want to ask how I can obtain SUMO network files such as highD_1.net.xml? Because I currently have another road network file built by JOSM, I want to convert it into a SUMO road network file, similar to what this repo does.

I guess you may have to look into [the label rule of the original version of OSM](https://wiki.openstreetmap.org/wiki/Tags) and revise the OSM file. My current version of `.net.xml` files are manually created by SUMO's built-in tool netedit.

**Comment by gcruiser** [comment]
> > I understand, thanks for your suggestion. I want to ask how I can obtain SUMO network files such as highD_1.net.xml? Because I currently have another road network file built by JOSM, I want to convert it into a SUMO road network file, similar to what this repo does.
> 
> I guess you may have to look into [the label rule of the original version of OSM](https://wiki.openstreetmap.org/wiki/Tags) and revise the OSM file. My current version of `.net.xml` files are manually created by SUMO's built-in tool netedit.
 
Thanks alot
